//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
=======
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
>>>>>>> 8eecfa87621eb648cc244f03d152c1c03fb39371
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdicionesxCliente
    {
        public int idAdicionesxCliente { get; set; }
        public Nullable<int> idAdicion { get; set; }
        public Nullable<int> idCliente { get; set; }
    
<<<<<<< HEAD
        public virtual Adiciones Adiciones { get; set; }
        public virtual Clientes Clientes { get; set; }
=======
        public virtual Adicione Adicione { get; set; }
        public virtual Cliente Cliente { get; set; }
>>>>>>> 8eecfa87621eb648cc244f03d152c1c03fb39371
    }
}
