//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id { get; set; }
        public string cedula { get; set; }
        public int genero { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string direccion_fisica { get; set; }
        public string telefono_principal { get; set; }
        public string telefono_secundario { get; set; }
        public string correo_electronico { get; set; }
        public int id_provincia { get; set; }
        public int id_canton { get; set; }
        public int id_distrito { get; set; }
        public int id_usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
